package com.platform.identityaccess.domain;

public enum PermissionCode {
    DEPARTMENT_VIEW,
    DEPARTMENT_CREATE,
    PROGRAM_FILIERE_VIEW,
    PROGRAM_FILIERE_CREATE,
    DEGREE_CYCLE_VIEW,
    DEGREE_CYCLE_CREATE,
    PROGRAM_PATH_VIEW,
    PROGRAM_PATH_CREATE,
    ACADEMIC_LEVEL_VIEW,
    ACADEMIC_LEVEL_CREATE,
    ACADEMIC_YEAR_VIEW,
    ACADEMIC_YEAR_CREATE,
    SEMESTER_VIEW,
    SEMESTER_CREATE,
    SUBJECT_MODULE_VIEW,
    SUBJECT_MODULE_CREATE,
    CLASS_GROUP_VIEW,
    CLASS_GROUP_CREATE,
    STUDENT_VIEW,
    STUDENT_CREATE,
    PROFESSOR_VIEW,
    PROFESSOR_CREATE
}
