import { useState } from "react";
import type { FinalResult } from "@/features/assessment/api/final-results-api";
import type { GradeDocumentContext } from "@/features/assessment/utils/save-student-session-grades-pdf";
import { saveModuleFinalResultsPdf } from "@/features/assessment/utils/save-final-results-pdf";

interface Props {
  context: GradeDocumentContext;
  isLoading: boolean;
  results: FinalResult[];
}

const resultLabels = { V: "Validated", AV: "Compensated", NV: "Not validated" } as const;

export function ProfessorFinalGradeSheet({ context, isLoading, results }: Props) {
  const [exporting, setExporting] = useState(false);

  if (isLoading) return <div className="panel-empty">Loading final results...</div>;
  if (!results.length) return <div className="panel-empty"><strong>Final results are not available yet.</strong><p>Academic administration generates them after the required session grades are published.</p></div>;

  const validated = results.filter((result) => result.resultStatus === "V").length;
  const compensated = results.filter((result) => result.resultStatus === "AV").length;
  const notValidated = results.filter((result) => result.resultStatus === "NV").length;

  async function download() {
    setExporting(true);
    try { await saveModuleFinalResultsPdf(results, context); } finally { setExporting(false); }
  }

  return <div className="professor-grade-sheet">
    <header className="professor-grade-summary">
      <div><span className="professor-grade-status">FINAL</span><strong>{results[0].subjectModuleTitle}</strong><small>Read-only results generated by academic administration</small></div>
      <dl><div><dt>Students</dt><dd>{results.length}</dd></div><div><dt>Validated</dt><dd>{validated}</dd></div><div><dt>Compensated</dt><dd>{compensated}</dd></div><div><dt>Not validated</dt><dd>{notValidated}</dd></div></dl>
    </header>
    <div className="professor-grade-table-wrap"><table className="professor-grade-table"><thead><tr><th>Student</th><th>Apogee</th><th>Inscription</th><th>Final grade / 20</th><th>Result</th></tr></thead><tbody>{results.map((result) => <tr key={result.moduleRegistrationId}><td><strong>{result.firstName} {result.lastName}</strong></td><td>{result.apogeeCode}</td><td>{result.inscriptionNumber === 1 ? "First" : `${result.inscriptionNumber}${result.inscriptionNumber === 2 ? "nd" : "th"}`}</td><td><strong className={result.resultStatus === "NV" ? "grade-value--not-validated" : undefined}>{result.finalGrade?.toFixed(2) ?? "—"}</strong></td><td><span className={`final-result-status final-result-status--${result.resultStatus?.toLowerCase() ?? "pending"}`}>{result.resultStatus ? resultLabels[result.resultStatus] : "Pending"}</span></td></tr>)}</tbody></table></div>
    <footer className="professor-grade-actions"><p>Final grades cannot be edited by the Professor.</p><button className="record-open-link professor-grade-download-link" disabled={exporting} onClick={download} type="button">{exporting ? "Preparing..." : "Download PDF"}</button></footer>
  </div>;
}
