package com.platform.universitygovernance.academicruleprofile.domain.rules;

public enum AcademicMetric {
    MODULE_FINAL_GRADE,
    MODULE_INSCRIPTION_NUMBER,
    SEMESTER_AVERAGE,
    INDIVIDUALLY_VALIDATED_MODULE_COUNT,
    NON_VALIDATED_MODULE_COUNT,
    MINIMUM_NON_VALIDATED_MODULE_GRADE,
    ANNUAL_AVERAGE,
    NON_VALIDATED_SEMESTER_COUNT,
    ACADEMIC_LEVEL_VALIDATED,
    OUTSTANDING_MODULE_COUNT,
    EXHAUSTED_MODULE_INSCRIPTION_COUNT
}
