package com.platform.universitygovernance.academicruleprofile.domain.rules;

public enum ProfileVariable {
    MODULE_VALIDATION_THRESHOLD,
    COMPENSATION_MINIMUM_THRESHOLD,
    SEMESTER_VALIDATION_AVERAGE,
    ANNUAL_VALIDATION_AVERAGE,
    MINIMUM_INDIVIDUALLY_VALIDATED_MODULES_PER_SEMESTER,
    MAXIMUM_NON_VALIDATED_MODULES_PER_SEMESTER,
    MINIMUM_INDIVIDUALLY_VALIDATED_MODULES_PER_ACADEMIC_LEVEL,
    MAXIMUM_MODULE_INSCRIPTIONS,
    MAXIMUM_CARRIED_MODULES
}
